### ISSUE TITLE
DE-31 Documentation missing

### ISSUE THREAD

**Issue by Dragnell87** [ubuntu/adsys#122]
Good day everyone i have some question about the documentation:
Beyond what  the usage page proposed there are some point that are no clarified:
Requirements: Compatible with ? Windows Server 2012R2,  2016,  2019 ?

sssd requires a modification in order to adsys to allow the client to login: ad_server = ad.example.com otherwise it will complaint about no having an AD server define in the sssd.conf file.

ADMX files:
The GPC Templates show in this post from where are they gather ? adsysctl policy admx all ?
https://discourse.ubuntu.com/t/desktop-team-updates-monday-25th-january-2021/20519/3

Thanks

**Comment by didrocks** [comment]
@Dragnell87: hey! Thanks for reporting this bug :)

Some documentation will be written soon, we just need to find some time for that, but we agree it’s missing. Expecting adsys to be mostly used with LTSes, our goal will be to deliver it at the same time we backport it to 20.04 LTS. We tested it with Windows Server 2019, but there is nothing that should prevent this to work with previous Windows Server versions.

On your sssd question, if probably configured (domain join as we do in ubiquity for instance) and your DNS answers to SRV requests , you shouldn’t need any change and ad_server should be present with the correct address. How was it missing for you?

On ADMX, the templates are indeed embedded in the `adsysctl policy admx <type>` command. You can find them also in the github repo here: https://github.com/ubuntu/adsys/tree/main/internal/policies/ad/definitions/policy/Ubuntu

**Comment by Dragnell87** [comment]
Thanks for the fast reply, on sssd: it was post install actually, regardless, you are probably right about the DNS not answering SRV record, i will check that.

On ADMX, well i did try both but fail to get imported in the in a Windows Server 2012R2, i will spin a 2019 to test drive it. In any case, do you have any fallowup documentation  for adding admx files to Windows AD?

Thanks again, for your time

**Comment by didrocks** [comment]
@Dragnell87 We’ll ping you if you don’t mind once we get the documentation ready (and probably some videos). It should be quite easy to setup though (just install adsys, ensure that sssd is correctly configured and log with an AD user). Then, you should see the ubuntu specific configuration you set applied.

**Comment by Dragnell87** [comment]
OK, that is no problem. I will try to enrol again after set the dns again. Eager to see the documentation. Thanks
