### ISSUE TITLE
Feature request: Implement Azure AD support

### ISSUE THREAD

**Issue by stdevel** [ubuntu/adsys#130]
Hello everyone,

I was just wondering whether Azure AD support is planned for the future? As a lot of customers prefer using Azure AD instead of local AD instances this would be a great functionality in my opinion.

I understand that Azure AD is completely different from a technical perspective.

**Comment by jibel** [comment]
Hi stdevel,

Yes this is on the roadmap, however we cannot commit to any date for the moment.

**Comment by thawkins** [comment]
any movement on this feature request?

**Comment by jibel** [comment]
AD and Azure AD are two different technologies and we are working on a separate project to support cloud identity https://github.com/ubuntu/authd . authd currently supports oidc and entra id (azure) with the device code flow.

I'm closing this issue.
