### ISSUE TITLE
Clarify supported releases

### ISSUE THREAD

**Issue by vchernin** [ubuntu/adsys#162]
The [wiki](https://github.com/ubuntu/adsys/wiki/1.-Welcome#supported-releases) states ADSys is supported on Ubuntu starting from 20.04.4 LTS. This might be a mistake as the [latest Ubuntu LTS release is 20.04.2](https://ubuntu.com/download/desktop). If not a mistake it should be specified 20.04.4 is not yet released.

**Comment by jibel** [comment]
Thanks for reporting this. Indeed .4 is still far away. Fixed.
