### ISSUE TITLE
Azure Active Directory Domain causes installation to get stuck

### ISSUE THREAD

**Issue by lzinga** [ubuntu/adsys#187]
## Description

When attempting to join a domain with a url path the installation process of Ubuntu 21.04 halts and you are unable to do anything to cancel or revert the change with out rebooting.

## Reproduction
Run through the installation of Ubuntu 21.04 and attempt to place a url into the Domain field, the url is pointing to an Azure Active Directory, which I learned later that it wasn't supported yet. However, this still is a bug that causes the window to freeze and prevent continuation of setup.

![image](https://user-images.githubusercontent.com/9082450/125152942-442fc700-e105-11eb-9b2f-29c72f226eae.png)

### Environment
Running Windows 11 and Ubuntu 21.04 on Hyper-V

#### For ubuntu users, please run and copy the following
States cannot obtain the report for a package that is not installed.

**Comment by didrocks** [comment]
Thanks for reporting this bug and help making ubuntu better. Indeed, I’m unsure if there is any way to detect if the other side is an Azure AD, but we should do something about it.

However, this daemon isn’t the ubuntu installer, this should be reported against the ubuntu installer itself at https://launchpad.net/ubuntu/+source/ubiquity. Thanks a lot!
