### ISSUE TITLE
Stuck at install on 22.04 alpha

### ISSUE THREAD

**Issue by averyfreeman** [ubuntu/adsys#286]
Stuck at install on 22.04

**Thank you in advance for helping us to improve ADSys!**  
Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).

## Description

> Provide a clear and concise description of the issue, including what you expected to happen.
Expected:
Install `adsys` package through `apt`
Configure
Use

Actual:
`$ sudo apt install adsys` hangs at `adsys-gpo-refresh.service is a disabled or a static unit not running, not starting it.`
Waited overnight, came back, still stuck
`$ sudo dpkg -a --configure` fails 3x before `$ sudo dpkg -r adsys`

## Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.

Steps:
`$ sudo apt install -y adsys`

output:

```
Setting up adsys (0.8) ...
Created symlink /etc/systemd/user/default.target.wants/adsys-user-scripts.service → /usr/lib/systemd/user/adsys-user-scripts.service.
Created symlink /etc/systemd/system/multi-user.target.wants/adsys-boot.service → /lib/systemd/system/adsys-boot.service.
Created symlink /etc/systemd/system/timers.target.wants/adsys-gpo-refresh.timer → /lib/systemd/system/adsys-gpo-refresh.timer.
Created symlink /etc/systemd/system/default.target.wants/adsys-machine-scripts.service → /lib/systemd/system/adsys-machine-scripts.service.
Created symlink /etc/systemd/system/sockets.target.wants/adsysd.socket → /lib/systemd/system/adsysd.socket.
adsys-gpo-refresh.service is a disabled or a static unit not running, not starting it.
adsysd.service is a disabled or a static unit not running, not starting it.

Terminated

$ sudo rm -rf /var/lib/dpkg/lock* 

(tried 3x)

$ sudo dpkg --configure -a
Setting up adsys (0.8) ...
adsys-gpo-refresh.service is a disabled or a static unit not running, not starting it.

**[stuck]**

^CCould not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142. 
dpkg: error processing package adsys (--configure):
 installed adsys package post-installation script subprocess was interrupted

$ sudo dpkg -r adsys
```
>
> Where applicable, please include:
>
> * Code sample to reproduce the issue
> * Log files (redact/remove sensitive information)
> * Application settings (redact/remove sensitive information)
> * Screenshots

### Environment

> Please provide the following:

#### For ubuntu users, please run and copy the following

1. `ubuntu-bug adsys --save=/tmp/report`
1. Copy paste below `/tmp/report` content:

```raw
ProblemType: Bug
ApportVersion: 2.20.11-0ubuntu77
Architecture: amd64
CasperMD5CheckResult: pass
Date: Tue Feb 22 07:14:59 2022
DistroRelease: Ubuntu 22.04
InstallationDate: Installed on 2022-02-17 (4 days ago)
InstallationMedia: Ubuntu 22.04 LTS "Jammy Jellyfish" - Alpha amd64 (20220202)
NonfreeKernelModules: zfs zunicode zavl icp zcommon znvpair
Package: adsys (not installed)
ProcCpuinfoMinimal:
 processor	: 11
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 158
 model name	: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 stepping	: 10
 microcode	: 0xec
 cpu MHz		: 2200.000
 cache size	: 9216 KB
 physical id	: 0
 siblings	: 12
 core id		: 5
 cpu cores	: 6
 apicid		: 11
 initial apicid	: 11
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 22
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
 vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
 bogomips	: 4399.99
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 39 bits physical, 48 bits virtual
 power management:
ProcEnviron:
 LANGUAGE=
 TERM=xterm-256color
 PATH=(custom, no user)
 LANG=en_US.UTF-8
 SHELL=/bin/bash
ProcVersionSignature: Ubuntu 5.15.0-22.22-generic 5.15.19
SourcePackage: adsys
Tags:  jammy
Uname: Linux 5.15.0-22-generic x86_64
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True
```

#### Installed versions

* OS: (`/etc/os-release`)
```
PRETTY_NAME="Ubuntu Jammy Jellyfish (development branch)"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* ADSys version: (`adsysctl version` output)
Could not install adsys

#### Additional context

> Add any other context about the problem here.

Sorry, I didn't realize this is unsupported in 22.04 until I went to file bug report and saw another issue asking about ver. support status.

report FYI re: future support `jammy`

**Comment by didrocks** [comment]
Thanks for reporting this bug! Sorry for not getting back earlier, but a lot of things changed in jammy and we couldn’t reproduce the issue. Is it still an issue you are having with finale version?
