### ISSUE TITLE
It is necessary to add a case that does not use quotation marks.

### ISSUE THREAD

**Issue by bdh1993** [ubuntu/adsys#291]
>**Please do not report security vulnerabilities here**  
>Use [launchpad ADSys private bugs](https://bugs.launchpad.net/ubuntu/+source/adsys/+filebug) which is monitored by our security team. On ubuntu machine, it’s best to use `ubuntu-bug adsys` to collect relevant information.

**Thank you in advance for helping us to improve ADSys!**  
Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).

## Describe the problem you'd like to have solved

I made a policy to adjust the screen saver time by modifying the admx and adml files.
I used the "meta:s" option, but it was a problem in this part.
Quotations mark must not be used to implement the policy.
When using quotation marks, the dconf policy and gsetting policy are displayed differently as shown in the following image.

![01](https://user-images.githubusercontent.com/58254473/156514301-7c6a1a80-a78d-4438-8359-63d0e1a2fa86.png)

I entered it on the AD server.
![02](https://user-images.githubusercontent.com/58254473/156515861-810e095f-0fe9-440b-b6fc-d71af2c06b06.png)

It was confirmed in "/etc/dconf/db/user.d/adsys".
![image](https://user-images.githubusercontent.com/58254473/156516085-395e6d9e-8137-4ec2-9ce7-2fee4866c360.png)

## Describe the ideal solution

Add meta option of string type that removes quotation marks

**Comment by didrocks** [comment]
idle-delay is type u, isn’t it? `/usr/share/glib-2.0/schemas/org.gnome.desktop.session.gschema.xml`. If you mark it as such, it should work correctly (it will be display as an uint in the UI). Do you mind sharing the admx/adml you created?

**Comment by bdh1993** [comment]
Thank you for your help

I confirmed that it was type u and changed it.

The AD server entered uint32 500 without quotation marks. (ex. uint32 500)

It worked!

However, it did not work if only numbers were entered. (ex. 400)

This seems to be the difference between dconf and gsetting.

**Comment by didrocks** [comment]
Yes! gsettings has knowledge about type and enforces them.
dconf, is just a backend which store things as you give to it. No type enforcement.

gsettings then write to dconf, with the correct format to hint the type.

Do not hesitate to tell us about your adsys experience in the future :)
