### ISSUE TITLE
Unable to login as a user of the joined Active Directory

### ISSUE THREAD

**Issue by bdh1993** [ubuntu/adsys#300]
>**Please do not report security vulnerabilities here**  
>Use [launchpad ADSys private bugs](https://bugs.launchpad.net/ubuntu/+source/adsys/+filebug) which is monitored by our security team. On ubuntu machine, it’s best to use `ubuntu-bug adsys` to collect relevant information.

**Thank you in advance for helping us to improve ADSys!**  
Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).

## Description

Unable to login as a user of the joined Active Directory

Here my error message.
sudo login > user > passwd > error
![image](https://user-images.githubusercontent.com/58254473/158292723-be16f607-2d6d-4fd2-86ba-71c2f4c58f0e.png)

## Reproduction

It is presumed that this problem occurred when ADCS(Active Drictory Certificate Service) was added, but it is not clear.
Linux OS was the same setting.
I tried setting up after reading wiki, but I couldn't solve it.

- Login Success : ![image](https://user-images.githubusercontent.com/58254473/158294936-e2e72651-dc20-4168-9217-032c236ca945.png)
- Login Error : ![image](https://user-images.githubusercontent.com/58254473/158294929-6a1a49ae-bebe-48ac-a95a-d76936dd5e16.png)

### - same settings

```
Linux
1. Install package (realmd, sssd, sssd-tools, libnss-sss, libpam-sss, adcli, samba-common-bin, oddjob, oddjob-mkhomedir)
2. Join AD (sudo realm join -U $AD $Domain > Check realm list > join is OK)
3. Change /usr/share/pam-configs/mkhomedir > sudo pam-auth-update
4. sudo realm permit user@domain
5. Test login (sudo login > user@domain > passwd > login is OK)
  - Before installing the adsys.
6. Install adsys package and make /etc/adsys.yaml

Window
1. Install Window server OS
2. Make AD domain
```

### - different settings
```
Window
1. AD CS, IIS
```

I can't login after installing the adsys package.
I think it's a problem related to the certificate.
I referred to the following link.
https://ubuntu.com/server/docs/service-sssd
My sssd setting is as follows.
![image](https://user-images.githubusercontent.com/58254473/158307831-9da5a74e-f5b2-4645-9945-438f5b766a1c.png)

My /etc/adsys.yaml is as follows.
![image](https://user-images.githubusercontent.com/58254473/158312619-a5bd9675-a6ba-4845-83e5-427f63ea28e2.png)

Is there a setting that I made a mistake in?
Should id_provider be set to ldap to set the certificate?
I need help.

### Environment

* ADSys version: 0.8~22.04

**Comment by rsbrux** [comment]
I have a similar problem, but the error message reads:
"Error from server: error while updating policy: can't get policies for <FQDN>: requested a type computer of <FQDN> which isn't current host <simple hostname>."
This despite the fact that "hostname", "hostname -f" and "hostnamectl status" all deliver the FQDN. Where else can adsys be looking for <servername>?
Please see [this post](https://askubuntu.com/questions/1425289/stuck-joining-ubuntu-studio-22-04-1-to-active-directory) on askUbuntu for further details.

**Comment by jibel** [comment]
I'm closing this report do to the lack of feedback from the OP. Feel free to reopen if it is still an issue for you.
