### ISSUE TITLE
Does it work with fedora?

### ISSUE THREAD

**Issue by iMonZ** [ubuntu/adsys#338]
Does this work with Fedora too?
Since Ubuntu is switching soon to Flutter I am forced to switch to fedora.
So is this working there as well?

**Comment by didrocks** [comment]
I don’t really see why you think Ubuntu is using Flutter apart from the newly coming installer.

Anyway, I don’t know if adsys is packaged on Fedora, please check with the Fedora community on it. There is no technical reason it won’t and they should be able to generate admx/adml compatible with it, alongside with a service to enable more features.

**Comment by iMonZ** [comment]
> I don’t really see why you think Ubuntu is using Flutter apart from the newly coming installer.
> 
> Anyway, I don’t know if adsys is packaged on Fedora, please check with the Fedora community on it. There is no technical reason it won’t and they should be able to generate admx/adml compatible with it, alongside with a service to enable more features.

The use of flutter at all makes Ubuntu very unattractive.
