### ISSUE TITLE
adsys proxy settings

### ISSUE THREAD

**Issue by aliadnan5505** [ubuntu/adsys#347]
Hello,

I am not able to find proxy settings configuration in admx/adml file for GPO implementation in Ubuntu clients.

Is there any settings for proxy server configuration in GPO?

**Comment by aliadnan5505** [comment]
![gpo_widget_decimal](https://user-images.githubusercontent.com/93698717/173498013-f3d92902-88b1-40f7-9fc1-f987b2fbff92.png)

where to find this setting?? this image is the github wiki page

**Comment by didrocks** [comment]
Hey [aliadnan5505](https://github.com/aliadnan5505),
This settings is not available anymore, as it is only read and applied by GNOME application, but not by the system wide configuration. This created confusions and thus, has been removed.

The numeric widget is still available as long as the entry is of a numeric type.
I’m tagging thus this feature as a wishlist

**Comment by aliadnan5505** [comment]
So the proxy setting is still configurable?

I want to use this proxy setting for all ubuntu clients on LAN via GPO.

Can you provide me old ADMX & ADML files for proxy settings?

**Comment by aliadnan5505** [comment]
How can we develop this feature for proxy settings?

**Comment by didrocks** [comment]
Well, this is an opensource project, so anyone can contribute to it or pay someone to do this work. I’m sure also that Canonical (the company sponsoring this projects) have ways for customers to put that need higher on the priority list.

**Comment by aliadnan5505** [comment]
Is there any method to apply proxy settings in Ubuntu via GPO?

**Comment by didrocks** [comment]
None that I know of, see my previous answers.

**Comment by jibel** [comment]
Proxy settings has been implemented in ADSys [0.11.0](https://launchpad.net/ubuntu/+source/adsys/0.11.0) available in Lunar (23.04+)
