### ISSUE TITLE
Refactor watchdtui using the new bubbles `Validate` API

### ISSUE THREAD

**Issue by GabrielNagy** [ubuntu/adsys#375]
## Describe the problem you'd like to have solved

The new [bubbles](https://github.com/charmbracelet/bubbles/releases/tag/v0.12.0) release comes with a Validate API which we can use to validate our TUI inputs (directories and config file). Currently, validation is done via arbitrary functions that directly operate on the `textinput.Model` objects, e.g. https://github.com/ubuntu/adsys/blob/e298b39f930f3a62b6172a63462350fcbd5f0ef6/internal/watchdtui/watchdtui.go#L397-L435

## Describe the ideal solution

Input validation is done via the newly added API.

**Comment by jibel** [comment]
Fixed with https://github.com/ubuntu/adsys/commit/1f819dcab406c936a3a22737798acab4d1dde73a
