### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by tlcarpenter** [ubuntu/adsys#407]
>**Please do not report security vulnerabilities here**  
>Use [launchpad ADSys private bugs](https://bugs.launchpad.net/ubuntu/+source/adsys/+filebug) which is monitored by our security team. On ubuntu machine, it’s best to use `ubuntu-bug adsys` to collect relevant information.

**Thank you in advance for helping us to improve ADSys!**  
Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).

## Describe the problem you'd like to have solved
do you intend to support use of adsys on macOS

## Describe the ideal solution

provide more information about the macOS references in Readme.md

## Alternatives and current workarounds

n/a

### Environment

> Please provide the following:

#### For ubuntu users, please run and copy the following

1. `ubuntu-bug adsys --save=/tmp/report`
1. Copy paste below `/tmp/report` content:

```raw
COPY REPORT CONTENT HERE.
```

#### Installed versions

* OS: (`/etc/os-release`)
* ADSys version: (`adsysctl version` output)

#### Additional context

> Add any other context about the problem here.

**Comment by didrocks** [comment]
Hey, thanks for the suggestion! I’ll tag that as enhancement proposal. Adsys is focused on Linux environment right now (depending on systemd and other Linux technologies like polkit). However, it’s a free software, and anyone who want to contribute to grow MacOs support are more than welcome!

**Comment by tlcarpenter** [comment]
Found your project through this two-part post on Ubuntu's site

https://ubuntu.com/blog/new-active-directory-integration-features-in-ubuntu-22-04-part-1

https://ubuntu.com/blog/new-active-directory-integration-features-in-ubuntu-22-04-part-2-group-policy-objects

Saw macOS-related entries in Readme.md like

https://github.com/ubuntu/adsys#macos

Looked into solutions like those from Centrify for macOS and Linux, but we just don't have the funding for that. Thanks to you and the rest of the team for your efforts.
