### ISSUE TITLE
Applied command should says what rules are not applied

### ISSUE THREAD

**Issue by didrocks** [ubuntu/adsys#422]
Applied command should display a message for unapplied rules due to missing Ubuntu Pro subscription on the client (or don’t show them at all)

**Comment by denisonbarbosa** [comment]
Maybe we should list those under `adsysctl service status` message? Along with the subscription message, e.g.:
```txt
Ubuntu Pro subscription is not active on this machine. The following policies won't be applied: LIST OF DISABLED POLICIES
```

**Comment by didrocks** [comment]
I don’t think it’s worth it for now. This is more a documentation thingy IMHO. We should tell if Ubuntu Pro is enabled or not.
