### ISSUE TITLE
Mutexes should be transfered to a higher manager level

### ISSUE THREAD

**Issue by denisonbarbosa** [ubuntu/adsys#427]
Right now, mutexes are used to secure the application of the policies, but they are used locally by each policy handler. We could unify them in a single one controlled by the "global" manager.

**Comment by denisonbarbosa** [comment]
With each new manager, the mutexes get more complex. If we try to do it in the general manager, it would create more complexity than benefits so it's not worth.

**Comment by didrocks** [comment]
I still think that we shouldn't run a manager for the same user or machine in parallel. This is the abstraction that we should aim for IMHO. Then, additional locks can be localized inside the manager itself.

**Comment by denisonbarbosa** [comment]
Or we can go even further and maybe try something like a scheduler? TryLock to apply a certain policy, if it is not able to lock (which means we are already applying the policy type for another user) move the policy to the end of the queue and try to apply another one, repeat until error or all the policies are applied. Wdyt?

**Comment by didrocks** [comment]
I don’t think we should overcomplicate things.

What you are mentionning here, is applying every policies one after another, which is not what we want to do (apart from the interaction dconf/gdm for machine).

What we want is to run for a given user:
- all policy manager in parallel
- but not in parallel with the same policy manager for the same user.

**Comment by denisonbarbosa** [comment]
Ack. So it should be enough to have a `map[objectName]sync.Mutex` in the Manager type that locks when we are applying a policy for that specific object.

**Comment by didrocks** [comment]
I think a more elegant approach would be to embed a common type in each manager that handle that mutex. and this one is hooked up in ApplyPolicy() for each caller?

**Comment by denisonbarbosa** [comment]
Well, both work. I'm not sure if it's worth to propagate the mutex down the chain to the specific managers. It's not their responsibility to sync their applying process, this should be up to the "manager of all managers". Wdyt?

"One manager to rule them all, one manager to find them. One manager to bring them all, and in adsys bind them; In the land of Linux where the files lie"

Sorry, couldn't resist the joke :joy:

**Comment by didrocks** [comment]
> Well, both work. I'm not sure if it's worth to propagate the mutex down the chain to the specific managers. It's not their responsibility to sync their applying process, this should be up to the "manager of all managers". Wdyt?

Actually, it’s quite the opposite: technically, it’s not up to the caller to know that you can’t run this specific manager with the same argument concurrently.

However, I agree that in our case, it’s probably better to move that up to the main manager ruling them all :)
