### ISSUE TITLE
Policies manager don’t have tests for mount

### ISSUE THREAD

**Issue by didrocks** [ubuntu/adsys#450]
We noted it down for later, but after the integration tests, I think we missed track of it.

**Comment by denisonbarbosa** [comment]
Didn't we say that we would only integrate the mount tests in the policy manager when we had the machine mounts as well? From what I've seen in the TestApplyPolicies, we are only considering machine policies rather than user ones.

**Comment by didrocks** [comment]
You’re right, we are only calling them for machines, so let’s keep the bug opened for later reference, but it should be part of the computer part of the work there.

**Comment by denisonbarbosa** [comment]
The mount manager test cases in the policy manager tests are now merged into the system mounts feature branch and waiting to be merged into main with #544 .
