### ISSUE TITLE
Golden should always be normalized

### ISSUE THREAD

**Issue by didrocks** [ubuntu/adsys#453]
Golden file generation should use the same helper for normalizing the golden name.

We need then to discuss if we shouldn’t have them by test group name, like `TestNew/Subtest/golden` or `golden/TestNew/Subtest`. This will need to take into account we have some fixtures per tests sometimes.

**Comment by denisonbarbosa** [comment]
I think it feels better to have them under `Test/Subtest/golden` and the fixtures under `Test/Subtest/fixtures`.
This way, we would have all files related to the subtest in a single tree, rather than having to look into two different trees to debug subtest related things, which makes more sense.

**Comment by didrocks** [comment]
Unfortunately, there are some issues in this organization: many tests composed a fix set of fixtures (not related to a single test or subtest) to produce golden files.

Then, the fixtures are shared and are directly under `testdata/`, which will make `golden` the only directory or file under `SubTest`. Also, note that `golden` is sometime a directory with multiple dirs and subdirs (file tree) and sometimes, it can be just a file (and in that case, having all them nearby, named after the subtest helps)

**Comment by didrocks** [comment]
I think we should review exactly what the different use cases we have, ways pros and cons. I’m not a big fan of the fixtures subdirectory, as said in my previous message, I prefer having it directly under the targeted directory.

**Comment by didrocks** [comment]
So, `testdata/t.Name()/golden/`.

Then, shared fixtures are directly under `testdata`.

```
func TestPath(t *testing.T) {
   // returns testdata/t.Name()
}
```

Everytime, t.Name() needs to be normalized.

Fixtures can either be global or picked by tests, depending on how much is in common.

**Comment by denisonbarbosa** [comment]
So, the GoldenPath will return a directory path. We have a testutils.LoadWithUpdateFromGolden, so what should we go for the "default golden name"?

**Comment by didrocks** [comment]
Not necessairly a directory, it could be a file one for simple golden ones. The goal of this PR is to standardize against a single path, which is the one outlined above, to LoadWithUpdateFromGolden should just use that path.

Didn’t we use generic already in some of the function or was it only in aad-auth? If so, feel free to try to modernize it.
