### ISSUE TITLE
Investigate adding a tesutils helper function for tc.wantErr

### ISSUE THREAD

**Issue by didrocks** [ubuntu/adsys#455]
Can we base assertion on wantErr and stop the test if we need it?

This is what is in Skip() (but using private function).
```
	c.finished = true
	runtime.Goexit()
```

The issue is that we need to return/end with success. The helper may returns a bool otherwise, but is it a better syntax?

**Comment by denisonbarbosa** [comment]
Are you thinking about something like:
```go
# package testutils
func evaluateError(t *testing.T, err error, wantErr bool, stopOnError bool) {
    # if wantErr -> assert on error
    # if !wantErr -> assert on !error
    # if stopOnError -> t.Fail
}
```

**Comment by didrocks** [comment]
hum, not really something like this. The part to stopOnError is rather ("stop the tests if condition matches"). I think we should give some try at some part (also, this should use require directly. If we want to assert, I don’t think we want to use the helper)

**Comment by denisonbarbosa** [comment]
As of today, Go does not provide a way to mark the test as `completed`, so we can't add a helper function to evaluate the error value and mark the test as finished if we wanted an error.
