### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by marta279** [ubuntu/adsys#458]
>**Please do not report security vulnerabilities here**  
>Use [launchpad ADSys private bugs](https://bugs.launchpad.net/ubuntu/+source/adsys/+filebug) which is monitored by our security team. On ubuntu machine, it’s best to use `ubuntu-bug adsys` to collect relevant information.

**Thank you in advance for helping us to improve ADSys!**  
Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).

## Describe the problem you'd like to have solved

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the ideal solution

> A clear and concise description of what you want to happen.

## Alternatives and current workarounds

> A clear and concise description of any alternatives you've considered or any workarounds that are currently in place.

### Environment

> Please provide the following:

#### For ubuntu users, please run and copy the following

1. `ubuntu-bug adsys --save=/tmp/report`
1. Copy paste below `/tmp/report` content:

```raw
COPY REPORT CONTENT HERE.
```

#### Installed versions

* OS: (`/etc/os-release`)
* ADSys version: (`adsysctl version` output)

#### Additional context

> Add any other context about the problem here.

**Comment by jibel** [comment]
Closing due to the lack of details.
