### ISSUE TITLE
Issues with FQDN Hostname in Environment with Subdomain

### ISSUE THREAD

**Issue by snussbaumermpreis** [ubuntu/adsys#523]
We have a Active Directory Domain with the following Scheme: <name.xy.xy>
So if I join a Host and set its Hostname to FQDN (hostname.name.xy.xy) as required for other services, adsysctl update does not work, the folliwing errors come up:

Searching for account failed with: Failed to find account hostname.name.xy.xy
Searching for account failed with: Failed to find account hostname.name

So in the second attempt adsys seems to try to use just the Hostname but as the domain has an additional level it does not remove the complete domainpart. The fix should be rather simple -> cut the hostname at the first dot.

**Comment by denisonbarbosa** [comment]
Hey @snussbaumermpreis, thanks for opening the issue. We weren't considering FQDN hostnames being set in /etc/hostname, so #526 should fix your problem! 
However, I would recommend you to take another look at your setup and check if you can configure the required fqdn, for the other services that you've mentioned, in /etc/hosts and keep the machine hostname single-labeled, as recommended by the [hostname man page](https://man7.org/linux/man-pages/man5/hostname.5.html) and the [debian documentation](https://www.debian.org/doc/manuals/debian-reference/ch03.en.html#_the_hostname).
