### ISSUE TITLE
ADSYS Authentication must be disabled for domain logins without @domain to work

### ISSUE THREAD

**Issue by Techy444** [ubuntu/adsys#550]
## Description

> I have  joined active directory windows domain successfully. I set /etc/sssd/sssd.conf  "use_fully_qualified_names =" to False. But when I login using just username, I get error message: "ubuntu domain login failure setting user credentials"

Only when I disable "adsys authentication" in command sudo pam-auth-update do domain logins work without @domain (I only found this out from looking online for solution from someone else having same issue)

Also, when I run command: adsysctl policy applied --details, I receive error: Error from server: error while displaying applied policies: no domain provided for user "xxxxxxx" and no default domain in sssd.conf

## Reproduction

> workaround: run command: sudo pam-auth-update then disable "adsys authentication"
Although I don't know what this is affecting by disabling adsys authentication.
>
> Where applicable, please include:
>
> * Code sample to reproduce the issue
> * Log files (redact/remove sensitive information)
> * Application settings (redact/remove sensitive information)
> * Screenshots

### Environment

> Please provide the following:

#### For Ubuntu users, please run and copy the following

1. `ubuntu-bug adsys --save=/tmp/report`
1. Copy paste below `/tmp/report` content:

```raw
ProblemType: Bug
ApportVersion: 2.20.11-0ubuntu82.2
Architecture: amd64
CasperMD5CheckResult: pass
CurrentDesktop: ubuntu:GNOME
Date: Mon Dec 12 18:57:12 2022
Dependencies:
 adduser 3.118ubuntu5
 apt 2.4.8
 apt-utils 2.4.8
 bind9-host 1:9.18.1-1ubuntu1.2
 bind9-libs 1:9.18.1-1ubuntu1.2
 ca-certificates 20211016ubuntu0.22.04.1
 cracklib-runtime 2.9.6-3.4build4
 dbus 1.12.20-2ubuntu4.1
 debconf 1.5.79ubuntu1
 debconf-i18n 1.5.79ubuntu1
 dirmngr 2.2.27-3ubuntu2.1
 distro-info 1.1build1
 distro-info-data 0.52ubuntu0.2
 dpkg 1.21.1ubuntu2.1
 file 1:5.41-3
 gcc-12-base 12.1.0-2ubuntu1~22.04
 gnupg 2.2.27-3ubuntu2.1
 gnupg-l10n 2.2.27-3ubuntu2.1
 gnupg-utils 2.2.27-3ubuntu2.1
 gpg 2.2.27-3ubuntu2.1
 gpg-agent 2.2.27-3ubuntu2.1
 gpg-wks-client 2.2.27-3ubuntu2.1
 gpg-wks-server 2.2.27-3ubuntu2.1
 gpgconf 2.2.27-3ubuntu2.1
 gpgsm 2.2.27-3ubuntu2.1
 gpgv 2.2.27-3ubuntu2.1
 init-system-helpers 1.62
 iso-codes 4.9.0-1
 ldap-utils 2.5.13+dfsg-0ubuntu0.22.04.1
 libacl1 2.3.1-1
 libapparmor1 3.0.4-2ubuntu2.1
 libapt-pkg6.0 2.4.8
 libassuan0 2.5.5-1build1
 libaudit-common 1:3.0.7-1build1
 libaudit1 1:3.0.7-1build1
 libavahi-client3 0.8-5ubuntu5
 libavahi-common-data 0.8-5ubuntu5
 libavahi-common3 0.8-5ubuntu5
 libbasicobjects0 0.6.2-1
 libblkid1 2.37.2-4ubuntu3
 libbsd0 0.11.5-1
 libbz2-1.0 1.0.8-5build1
 libc-ares2 1.18.1-1build1
 libc6 2.35-0ubuntu3.1
 libcap-ng0 0.7.9-2.2build3
 libcap2 1:2.44-1build3
 libcollection4 0.6.2-1
 libcom-err2 1.46.5-2ubuntu1.1
 libcrack2 2.9.6-3.4build4
 libcrypt1 1:4.4.27-1
 libcups2 2.4.1op1-1ubuntu4.1
 libdb5.3 5.3.28+dfsg1-0.8ubuntu3
 libdbus-1-3 1.12.20-2ubuntu4.1
 libdhash1 0.6.2-1
 libexpat1 2.4.7-1ubuntu0.2
 libffi8 3.4.2-4
 libgcc-s1 12.1.0-2ubuntu1~22.04
 libgcrypt20 1.9.4-3ubuntu3
 libglib2.0-0 2.72.4-0ubuntu1
 libglib2.0-data 2.72.4-0ubuntu1
 libgmp10 2:6.2.1+dfsg-3ubuntu1
 libgnutls30 3.7.3-4ubuntu1.1
 libgpg-error0 1.43-3
 libgpgme11 1.16.0-1.2ubuntu4
 libgpm2 1.20.7-10build1
 libgssapi-krb5-2 1.19.2-2
 libhogweed6 3.7.3-1build2
 libicu70 70.1-2
 libidn2-0 2.3.2-2build1
 libini-config5 0.6.2-1
 libipa-hbac0 2.6.3-1ubuntu3.2
 libjansson4 2.13.1-1.1build3
 libjson-c5 0.15-3~ubuntu1.22.04.1
 libjson-glib-1.0-0 1.6.6-1build1
 libjson-glib-1.0-common 1.6.6-1build1
 libk5crypto3 1.19.2-2
 libkeyutils1 1.6.1-2ubuntu3
 libkrb5-3 1.19.2-2
 libkrb5support0 1.19.2-2
 libksba8 1.6.0-2ubuntu0.1
 libldap-2.5-0 2.5.13+dfsg-0ubuntu0.22.04.1
 libldap-common 2.5.13+dfsg-0ubuntu0.22.04.1
 libldb2 2:2.4.4-0ubuntu0.1
 liblmdb0 0.9.24-1build2
 liblocale-gettext-perl 1.07-4build3
 liblz4-1 1.9.3-2build2
 liblzma5 5.2.5-2ubuntu1
 libmagic-mgc 1:5.41-3
 libmagic1 1:5.41-3
 libmaxminddb0 1.5.2-1build2
 libmd0 1.0.4-1build1
 libmount1 2.37.2-4ubuntu3
 libmpdec3 2.5.1-2build2
 libncursesw6 6.3-2
 libnettle8 3.7.3-1build2
 libnfsidmap1 1:2.6.1-1ubuntu1.2
 libnghttp2-14 1.43.0-1build3
 libnl-3-200 3.5.0-0.1
 libnl-route-3-200 3.5.0-0.1
 libnpth0 1.6-3build2
 libnsl2 1.3.0-2build2
 libnss-sss 2.6.3-1ubuntu3.2
 libp11-kit0 0.24.0-6build1
 libpam-modules 1.4.0-11ubuntu2
 libpam-modules-bin 1.4.0-11ubuntu2
 libpam-pwquality 1.4.4-1build2
 libpam-runtime 1.4.0-11ubuntu2
 libpam-sss 2.6.3-1ubuntu3.2
 libpam0g 1.4.0-11ubuntu2
 libpath-utils1 0.6.2-1
 libpcre2-8-0 10.39-3ubuntu0.1
 libpcre3 2:8.39-13ubuntu0.22.04.1
 libpolkit-gobject-1-0 0.105-33
 libpopt0 1.18-3build1
 libpwquality-common 1.4.4-1build2
 libpwquality1 1.4.4-1build2
 libpython3-stdlib 3.10.6-1~22.04
 libpython3.10 3.10.6-1~22.04.2
 libpython3.10-minimal 3.10.6-1~22.04.2
 libpython3.10-stdlib 3.10.6-1~22.04.2
 libreadline8 8.1.2-1
 libref-array1 0.6.2-1
 libsasl2-2 2.1.27+dfsg2-3ubuntu1
 libsasl2-modules 2.1.27+dfsg2-3ubuntu1
 libsasl2-modules-db 2.1.27+dfsg2-3ubuntu1
 libsasl2-modules-gssapi-mit 2.1.27+dfsg2-3ubuntu1
 libseccomp2 2.5.3-2ubuntu2
 libselinux1 3.3-1build2
 libsemanage-common 3.3-1build2
 libsemanage2 3.3-1build2
 libsepol2 3.3-1build1
 libsmartcols1 2.37.2-4ubuntu3
 libsmbclient 2:4.15.9+dfsg-0ubuntu0.3
 libsqlite3-0 3.37.2-2ubuntu0.1
 libssl3 3.0.2-0ubuntu1.7
 libsss-certmap0 2.6.3-1ubuntu3.2
 libsss-idmap0 2.6.3-1ubuntu3.2
 libsss-nss-idmap0 2.6.3-1ubuntu3.2
 libstdc++6 12.1.0-2ubuntu1~22.04
 libsystemd0 249.11-0ubuntu3.6
 libtalloc2 2.3.3-2build1
 libtasn1-6 4.18.0-4build1
 libtdb1 1.4.5-2build1
 libtevent0 0.11.0-1build1
 libtext-charwidth-perl 0.04-10build3
 libtext-iconv-perl 1.7-7build3
 libtext-wrapi18n-perl 0.06-9
 libtinfo6 6.3-2
 libtirpc-common 1.3.2-2ubuntu0.1
 libtirpc3 1.3.2-2ubuntu0.1
 libudev1 249.11-0ubuntu3.6
 libunistring2 1.0-1
 libuuid1 2.37.2-4ubuntu3
 libuv1 1.43.0-1
 libwbclient0 2:4.15.9+dfsg-0ubuntu0.3
 libxml2 2.9.13+dfsg-1ubuntu0.2
 libxxhash0 0.8.1-1
 libyaml-0-2 0.2.2-1build2
 libzstd1 1.4.8+dfsg-3build1
 lsb-base 11.1.0ubuntu4
 lsb-release 11.1.0ubuntu4
 media-types 7.0.0
 openssl 3.0.2-0ubuntu1.7
 passwd 1:4.8.1-2ubuntu2.1
 perl-base 5.34.0-3ubuntu1.1
 pinentry-curses 1.1.1-1build2
 python-apt-common 2.3.0ubuntu2.1
 python3 3.10.6-1~22.04
 python3-apt 2.3.0ubuntu2.1
 python3-gpg 1.16.0-1.2ubuntu4
 python3-ldb 2:2.4.4-0ubuntu0.1
 python3-minimal 3.10.6-1~22.04
 python3-pkg-resources 59.6.0-1.2
 python3-samba 2:4.15.9+dfsg-0ubuntu0.3
 python3-sss 2.6.3-1ubuntu3.2
 python3-talloc 2.3.3-2build1
 python3-tdb 1.4.5-2build1
 python3-yaml 5.4.1-1ubuntu1
 python3.10 3.10.6-1~22.04.2
 python3.10-minimal 3.10.6-1~22.04.2
 readline-common 8.1.2-1
 samba-dsdb-modules 2:4.15.9+dfsg-0ubuntu0.3
 samba-libs 2:4.15.9+dfsg-0ubuntu0.3
 sensible-utils 0.0.17
 shared-mime-info 2.1-2
 sssd 2.6.3-1ubuntu3.2
 sssd-ad 2.6.3-1ubuntu3.2
 sssd-ad-common 2.6.3-1ubuntu3.2
 sssd-common 2.6.3-1ubuntu3.2
 sssd-dbus 2.6.3-1ubuntu3.2
 sssd-ipa 2.6.3-1ubuntu3.2
 sssd-krb5 2.6.3-1ubuntu3.2
 sssd-krb5-common 2.6.3-1ubuntu3.2
 sssd-ldap 2.6.3-1ubuntu3.2
 sssd-proxy 2.6.3-1ubuntu3.2
 tar 1.34+dfsg-1build3
 ubuntu-advantage-desktop-daemon 1.9~22.04.1
 ubuntu-advantage-tools 27.12~22.04.1
 ubuntu-keyring 2021.03.26
 uuid-runtime 2.37.2-4ubuntu3
 wamerican 2020.12.07-2
 xdg-user-dirs 0.17-2ubuntu4
 zlib1g 1:1.2.11.dfsg-2ubuntu9.2
DistroRelease: Ubuntu 22.04
InstallationDate: Installed on 2022-12-04 (8 days ago)
InstallationMedia: Ubuntu 22.04 LTS "Jammy Jellyfish" - Release amd64 (20220419)
Package: adsys 0.9.2~22.04
PackageArchitecture: amd64
ProcCpuinfoMinimal:
 processor	: 3
 vendor_id	: GenuineIntel
 cpu family	: 15
 model		: 6
 model name	: Common KVM processor
 stepping	: 1
 microcode	: 0x1
 cpu MHz		: 2195.156
 cache size	: 16384 KB
 physical id	: 0
 siblings	: 4
 core id		: 3
 cpu cores	: 4
 apicid		: 3
 initial apicid	: 3
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 13
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
 bogomips	: 4390.31
 clflush size	: 64
 cache_alignment	: 128
 address sizes	: 40 bits physical, 48 bits virtual
 power management:
ProcEnviron:
 TERM=xterm-256color
 PATH=(custom, no username)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
ProcVersionSignature: Ubuntu 5.15.0-56.62-generic 5.15.64
RelatedPackageVersions:
 sssd          2.6.3-1ubuntu3.2
 python3-samba 2:4.15.9+dfsg-0ubuntu0.3
SourcePackage: adsys
Tags:  wayland-session jammy
Uname: Linux 5.15.0-56-generic x86_64
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True
modified.conffile..etc.polkit-1.localauthority.conf.d.99-adsys-privilege-enforcement.conf: [deleted]
modified.conffile..etc.sudoers.d.99-adsys-privilege-enforcement: [deleted]
```

#### Relevant AD information

If AD authentication works but adsys fails to fetch GPOs (e.g. you see `can't get policies` errors on login), please perform the following steps:

1. Add the following to `/etc/samba/smb.conf`:
```
log level = 10
```
2. Run `sudo login user@domain` in a terminal, replacing with your AD credentials
3. Paste the output in the bug report

/etc/samba does not exist on ubuntu

#### Installed versions

* OS: (`/etc/os-release`) -> this directory does not exist on my ubuntu desktop
* ADSys version: (`adsysctl version` output)

adsysctl 0.9.2~22.04
adsysd 0.9.2~22.04

#### Additional context

> Add any other context about the problem here.

**Comment by denisonbarbosa** [comment]
Hey @Techy444, thanks for opening the issue. Based on the error message that you provided, it looks like you don't have any default domain configured in your sssd.conf. This means that adsys will not be able to figure out which domain you are trying to log into when using a username without domain. You can fix it by setting the parameter `default_domain_suffix=domain.com`. Just a reminder that, if you set this parameter, users from another domain would need to use the fully qualified name in order to authenticate against the correct one.

Considering that the default option in sssd.conf for `use_fully_qualified_names` is False, it seems weird that you are having this problem. Is it the first time that you are logging into this account in your machine or did you log in previously?

Ps.: It's also really strange that you don't have /etc/samba/smb.conf neither /etc/os-release. The default smb.conf can be located under `/usr/share/samba/smb.conf` so you can restore it with ```bash sudo cp /usr/share/samba/smb.conf /etc/samba/smb.conf```. The `/etc/os-release` also should have a copy under `/usr/lib/os-release`, so you can use the same cp command specified for the smb.conf to copy the os-release from /usr/lib to /etc/.

Hopefully this will help you fix your problem or at least help you provide a bit more information when settting the `log level = 10` in /etc/samba/smb.conf. Let me know if this helped you or not!

**Comment by Techy444** [comment]
No problem!

I added:  default_domain_suffix=mydomainname.com to /etc/sssd/sssd.conf

Then I disabled adsys authentication but it still requires me to add the @domain.com at the end of the username.

It occurs on first time logging in and already logged in domain users. However, when I set it up the very first time I swear it worked without the @domain.com on the very first login then it stops working after.

I don't even have the /usr/share/samba location. It doesn't exist. Same goes for /etc/os-release. Did I miss an install command that was supposed to install these for me?

**Comment by Techy444** [comment]
Im going to just re-install ubuntu. Maybe I did something wrong.

**Comment by Techy444** [comment]
These are the original packages I installed on ubuntu: sudo apt -y install sssd-ad sssd-tools realmd adcli (got from a video)

Im guessing im missing some commands here

**Comment by denisonbarbosa** [comment]
You can run `sudo apt install --reinstall -o Dpkg::Options::="--force-confmiss" samba samba-common` in order to reinstall them and restore the conf files (purging and reinstalling also should work: `sudo apt purge samba samba-common && sudo apt install samba samba-common`) . Using --reinstall won't restore the /etc/samba/smb.conf, so you'll have to copy it from /usr/share/samba to /etc/samba. The same reinstall command applies to `os-release`, the package name is `base-files` (but **do not** use the purge alternative here).

I've tested the configuration settings that I've told you before and they work... I did the following steps:
1. Edit `/etc/sssd/sssd.conf` to add these settings under the shown sections:
```
[sssd]
default_domain = yourdomain.com
...

[domain/yourdomain.com]
use_fully_qualified_names = False
```
2. Run `sudo systemctl restart sssd.service`
3. Considering you had an user like `user@yourdomain.com`, now you can `sudo login user` and it will use the default domain (should have the same result as running `sudo login user@yourdomain.com`).

Hopefully, the first paragraph will help you get your samba setup fixed in order for us to try and get a bit more information about what is happening during the log in process.

**Comment by Techy444** [comment]
Thank you Denison, was taking a break from this. Started diving into some other options for AD-like systems but open source. Thank you very much and happy new year. Ill close the ticket as I got it working!
