### ISSUE TITLE
Build with go 1.21

### ISSUE THREAD

**Issue by GabrielNagy** [ubuntu/adsys#832]
### Is there an existing request for this feature?

- [X] I have searched the existing issues and found none that matched mine

### Describe the feature

Go 1.21 has been out for some time, once we start building with it we can:
- switch from exp/slices to stdlib slices package: https://github.com/ubuntu/adsys/pull/831
- use `cmp.Compare` with the new `slices.SortFunc`
- migrate from logrus to slog: https://github.com/ubuntu/adsys/issues/811

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
Upgrade to 1.21 and switch to slices fro; standard library in https://github.com/ubuntu/adsys/pull/831
So, only logrus remains in this issue.
