### ISSUE TITLE
docs recommend wrong directory ProgramData for deployment of Active Directory Watch Daemon (adwatchd.exe)

### ISSUE THREAD

**Issue by Buster-de** [ubuntu/adsys#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

https://github.com/ubuntu/adsys contains:

> After a successful installation, the `adwatchd.exe` executable will be available in the `/usr/share/adsys/windows` directory. We suggest you deploy this executable to a persistent directory of your choosing on the AD Domain Controller, such as `C:\ProgramData\Ubuntu\adsys\`.

ProgramData should only contain data, not executables.

"ProgramData" should be "Program Files", see https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-folderlocations-programdata

Configuration file can be located in ProgramData, if adwatchd.exe does not only support reading current directory.

### Steps to reproduce it

read https://canonical-adsys.readthedocs-hosted.com/en/latest/how-to/set-up-adwatchd/ and compare with Microsoft's recommendation

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
Thanks for reporting this issue. The doc will be updated accordingly.
