### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by spankaj13579** [ubuntu/adsys#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Bug on most systems ::: When interacting with the calendar feature in Ubuntu, an anomaly occurs when selecting dates belonging to January 2024. Despite being from the following year, these dates exhibit behavior and information associated with December 2023. For a more precise understanding, please refer to the attached video demonstration.
[Screencast from 18-12-23 04:04:24 PM IST.webm](https://github.com/ubuntu/adsys/assets/32034090/80c49190-6a59-4d14-abef-8ff38b44c4a0)

### Steps to reproduce it

1. Open the calendar in Ubuntu top bar.
2. click on the date which is not of december 2023 but shown in december calender.

### Environment
* adsys version: please run `adsysctl version`
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
adsys service logs can be acquired by running `adsysctl service cat -v`.
You can increase the amount of information displayed by increasing the verbosity level (-v) to -vv or -vvv.
```

### Application settings
Please redact/remove sensitive information:
```raw
Paste the contents of your adsys.yaml file here, if you created one.
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by didrocks** [comment]
Thanks for your contribution. However, this has nothing to do with adsys which is the project is for. Please open the bug against ubuntu itself: https://help.ubuntu.com/stable/ubuntu-help/report-ubuntu-bug.html.en.
Closing that one.
